function fields_to_log = DefineLoggedFields()
%% Define Logged Fields
% Returns a cell array defining the component and field names to be logged
% during the simulation.

fields_to_log = {...
    'tank', {'P', 'T', 'rho', 'm', 'state', 'X', ...
             'm_v', 'm_l', ...
             'u', 'u_v', 'u_l', ...
             's', 's_v', 's_l', ...
             'h', 'h_v', 'h_l', ...
             'cp', 'cp_v', 'cp_l', ...
             'cv', 'cv_v', 'cv_l', ...
             'H', 'S', 'rho_v', 'rho_l'}, ...
    'vent', {'mdot', 'ratio_Pcr', 'ratio_P'}, ...
    'inj',  {'mdot', 'P', 'T', 'rho', 'state', 'X', ...
             'u', 'u_v', 'u_l', ...
             's', 's_v', 's_l', ...
             'h', 'h_v', 'h_l', ...
             'cp', 'cp_v', 'cp_l', ...
             'cv', 'cv_v', 'cv_l', ...
             'rho_v', 'rho_l', ...
             'kappa', 'mdot_inc', 'mdot_HEM', ...
             'ratio_Pcr', 'ratio_P'}, ...
    'fuel', {'Gox', 'rdot', 'mdot', 'R_out', 'R', 'Ap', 'Ab', 'dR_m'}, ... % dR_m included
    'comb', {'mdot', 'OF', 'cstar', 'P', 'T', 'eta'}, ...
    'nozzle', {'Cf', 'F', 'Isp_sl'} ...
    };

end 